#!/bin/bash

# Nombre del archivo de entrada y salida
archivo_entrada="TEMPERATURES"
archivo_salida="salida.txt"

# Leer valores del archivo de entrada y unirlos en una sola línea
valores=$(cat "$archivo_entrada" | tr '\n' ' ')

# Construir la línea completa
linea="x $valores Infinity"

# Escribir la línea en el archivo de salida
echo "$linea" > "$archivo_salida"

